[versions]
agp = "8.6.0"
kotlin = "1.9.23"
androidx_test = "1.7.0"
androidx_test_ext = "1.3.0"
espresso_core = "3.7.0"
junit = "4.13.2"
min_sdk_version = "21"
compile_sdk_version = "36"
target_sdk_version = "36"
vanniktech-maven-publish = "0.33.0"
core_ktx_version = "1.16.0"
appcompat_version = "1.7.1"
activity_version = "1.9.2"
fragment_version = "1.8.3"
constraint_layout_version = "2.2.1"
navigation-fragment-ktx-version = "2.9.6"
navigation-ui-ktx-version = "2.9.6"

[libraries]
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx_test_rules = { module = "androidx.test:rules", version.ref = "androidx_test" }
androidx_test_runner = { module = "androidx.test:runner", version.ref = "androidx_test" }
androidx_test_ext_junit = { module = "androidx.test.ext:junit", version.ref = "androidx_test_ext" }
androidx_test_ext_junit_ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx_test_ext" }
espresso_core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso_core" }
androidx_core_ktx = { module = "androidx.core:core-ktx", version.ref = "core_ktx_version" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat_version" }
androidx_activity = { module = "androidx.activity:activity-ktx", version.ref = "activity_version" }
androidx_fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment_version" }
androidx_constraint_layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint_layout_version" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-ktx-version" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui-ktx-version" }

[plugins]
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }